
#!/bin/bash

#service mysql start

# Wait for MariaDB to start
#sleep 5

mysql -u root <<EOF
CREATE DATABASE IF NOT EXISTS \'${MYSQL_DATABASE}\';
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON \${MYSQL_DATABASE}\.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}' WITH GRANT OPTION;
UPDATE mysql.user SET password=password('$MYSQL_ROOT_PASSWORD') WHERE user='root';
FLUSH PRIVILEGES;
EOF


