CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON `${WP_DATABASE}`.* TO '${MYSQL_USER}'@'%' WITH GRANT OPTION;
UPDATE mysql.user SET password=PASSWORD('${MYSQL_ROOT_PASSWORD}') WHERE user='root';
FLUSH PRIVILEGES;


