version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./frontend:/usr/share/nginx/html
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/ft_transcendence
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ft_transcendence
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
