version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - my-network

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - my-network
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./srcs/requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my-network
    depends_on:
      - wordpress

networks:
  my-network:

