# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fcardina <fcardina@student.42roma.it>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/08 02:56:50 by fcardina          #+#    #+#              #
#    Updated: 2023/11/08 02:56:51 by fcardina         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@clear
	c++ *.cpp -Wall -Wextra -Werror -o phonebook
	./phonebook
	@rm phonebook