version: '3.7'

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/${USER_LOGIN}/data/mariadb:/var/lib/mysql
    networks:
      - my-network

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress:php8.2-fpm
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - /home/${USER_LOGIN}/data/wordpress:/var/www/html
    networks:
      - my-network
    depends_on:
      - mariadb

  nginx:
    image: nginx:alpine
    build:
      context: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx
      - /home/${USER_LOGIN}/data/wordpress:/var/www/html:ro
    networks:
      - my-network
    depends_on:
      - wordpress

networks:
  my-network:
    driver: bridge
