version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./data/nginx:/var/www/html
    networks:
      - inception_net

  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - inception_net

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - inception_net

networks:
  inception_net:
