version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
    volumes:
      - ../data/mariadb:/var/lib/mysql
    networks:
      - my-network

  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../data/wordpress:/var/www/html
    networks:
      - my-network
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx
    networks:
      - my-network
    depends_on:
      - wordpress

networks:
  my-network:
    driver: bridge
