#version: '3.7'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/${USER_LOGIN}/data/mariadb:/var/lib/mysql
    networks:
      - my-network
#    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./requirements/wordpress/conf:/etc/wordpress
      - /home/${USER_LOGIN}/data/wordpress:/var/www/html
    networks:
      - my-network
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx
      - /home/${USER_LOGIN}/data/wordpress:/var/www/html:ro
    networks:
      - my-network
    depends_on:
      - wordpress
    restart: unless-stopped

networks:
  my-network:
